### ISSUE TITLE
compositeEscape(j,j) not removing "-- INSERT --" in master branch build for Windows. 

### ISSUE THREAD

**Issue by vettukal** [asvetliakov/vscode-neovim#270]
Steps to reproduce:
1. I built a vsix in Ubuntu and installed it on windows VSCode from master branch.
2. Enter insert mode using `i`
3. Press `j`,`j`. This enters normal mode.
4. But string  "-- INSERT --" still remains in status bar.

Note:
Bug not present in ubuntu installation of master branch
Bug not present in official release of plugin in windows.
I also successfully reproduced the bug in clean portable VSCode

 Keybindings.json
```
[
    {
        "command": "vscode-neovim.compositeEscape1",
        "key": "j",
        "when": "neovim.mode == insert",
        "args": "j"
    }
]
```

Setting.json
```
{
    "vscode-neovim.highlightGroups.unknownHighlight": {
    
    },
    "vscode-neovim.neovimExecutablePaths.win32": "C:\\Users\\****\\Downloads\\Neovim\\bin\\nvim.exe"
}
```

**Comment by tfriedel** [comment]
I also have this problem when I use the escape key in the windows version.

**Comment by asvetliakov** [comment]
It exists however from the insert mode, right?

**Comment by tfriedel** [comment]
yes. I can enter insert mode and the string '-- INSERT --' appears. I leave the insert mode with escape and I'm obviously in normal mode, but the INSERT string remains forever.

**Comment by rafmsou** [comment]
Same kind of problem on macOS too.

**Comment by nwaywood** [comment]
I'm on macOS, when I press escape it removes `--INSERT--` string from the status bar, but when I press `jk` it does not

**Comment by theol0403** [comment]
For me on linux, doing `i<esc>` toggles `--INSERT--` on and then back off properly, but if I type anything during insert mode like `iz<esc>` the `--INSERT--` remains stuck on the status bar (until I do `i<esc>` again).

**Comment by Shatur95** [comment]
@theol0403, yes, same here.

**Comment by brentluna** [comment]
Same here on OSX. I sometimes get weird buggy behaviour when existing insert with `jk`. Wondering if it's related

**Comment by adamfeldman** [comment]
I'm also experiencing this, but more similar to #422 (which was closed as duplicate). 

I am _not_ using composite escape. `-- INSERT --` remains on the status bar when I exit NORMAL mode after having hit _any_ keys while in INSERT mode. If I just enter INSERT and then hit the escape key, the status bar updates as I expect.

**Comment by theol0403** [comment]
Fixed by #772

**Comment by Nivethan-Ar** [comment]
> doing `i<esc>` toggles `--INSERT--` on and then back off properly, but if I type anything during insert mode like `iz<esc>` the `--INSERT--` remains stuck on the status bar (until I do `i<esc>` again).

i still facing this issue on ubuntu! i removed everything inside my init.vim but still no luck!

**Comment by theol0403** [comment]
The merged PR has not been released yet unfortunately, due to all the maintainers not having the time to work on the project.

**Comment by Nivethan-Ar** [comment]
@theol0403 thanks for the info and i hope they merge the PR soon!
