### ISSUE TITLE
VSCode "Select all" does not work as expected in normal mode

### ISSUE THREAD

**Issue by ian-h-chamberlain** [asvetliakov/vscode-neovim#390]
It seems `vscode-neovim`'s handling of selection interferes with the builtin VSCode selection when in normal mode.

To reproduce, start in normal mode and use `<C-P>` to run VScode command "Select All" (`editor.action.selectAll`)

## Expected Behavior

The entire contents of a file are selected.

## Actual Behavior

If the cursor is already at the bottom of the file, the expected behavior happens (i.e. selection will be updated to include the whole file).

However, if the cursor is somewhere in the middle or top of the file, a selection of the whole file flashes but then is removed, and the cursor is moved to the bottom of the file.

## Workaround

`editor.action.selectAll` seems to work fine in insert mode, I believe this is because VSCode is controlling the cursor while in insert mode. Notably, the cursor is not moved to the bottom of the file and the window is not scrolled at all when the command is invoked.

Meanwhile, I can get something similar to insert-mode behavior by configuring this in `.vimrc`/`.init.vim`:

```vim
    nmap <D-a> ggVG
```

And the following in `keybindings.json`:

```jsonc
    {
        "key": "cmd+a",
        "when": "editorTextFocus && neovim.init",
        "command": "vscode-neovim.send",
        "args": "<D-a>"
    },
```

This does not actually fix the `editor.actions.selectAll` behavior, but gives me back a keyboard shortcut that I was used to using for "Select All".

## Environment

Extension details:
```
Name: Neo Vim
Id: asvetliakov.vscode-neovim
Description: Real VIM in your Visual Studio Code
Version: 0.0.63
Publisher: Alexey Svetliakov
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim
```
neovim details:
```
$ nvim --version 
NVIM v0.5.0-nightly-81-gaa4557920
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200908-21341-1cp1gl/build/config -I/tmp/neovim-20200908-21341-1cp1gl/src -I/usr/local/include -I/tmp/neovim-20200908-21341-1cp1gl/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200908-21341-1cp1gl/build/src/nvim/auto -I/tmp/neovim-20200908-21341-1cp1gl/build/include
Compiled by ichamberlain@Ians-Macbook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-aa45579/share/nvim"

Run :checkhealth for more info
```
VSCode details:
```
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Comment by miqrc** [comment]
I have the exact same issue. Tried to remap ctrl+a, but nothing happens.

**Comment by asvetliakov** [comment]
Can't reproduce with latest version so i guess this is fixed. Let me know if not

**Comment by introom** [comment]
I am facing the exact same issue as described in this thread with the latest version.

**Comment by wenfangdu** [comment]
@justinmk @theol0403 Please reopen this, it's still reproducible in the latest version.

**Comment by mitsukuri** [comment]
Ctrl+A seems to be broken in vscode-neovim `1.18.14` (vs codium `1.96.2`/neovim `0.10.2). It either doesn't work in any mode or sporadically pastes from clipboard in insert mode, can't figure out exact preconditions though.

**Comment by theol0403** [comment]
@mitsukuri sounds like you have it mapped to something

**Comment by theol0403** [comment]
@mitsukuri sounds like you have it mapped to something

**Comment by Akronae** [comment]
I had default `Ctrl + a` neovim VSCode keybindings I just had to remove
